services:
  frontend:
    # container_name: musikserver-client
    build: ./ # Location of our Dockerfile
    #volumes:
    #  - frontend-volume:/
    #  - './build:/usr/src/app'
    ports:
#      - '4202:4202'
      - '80:80'
    command: >
      npm run start-prod -- --host 0.0.0.0 --port 80
#nginx

#volumes:
#  frontend-volume:
