###
GET http://localhost:{{server.port}}/hello

###
GET http://localhost:{{server.port}}/musik/track/id/2

###
GET http://localhost:{{server.port}}/musik/track/get?genre=Kammermusik

###
GET http://localhost:{{server.port}}/musik/track/get?album=Fragile

###
GET http://localhost:{{server.port}}/musik/track/get?interpret=John

###
DELETE http://localhost:{{server.port}}/musik/track/remove?id=9652

###
GET http://localhost:{{server.port}}/musik/album/id/1

###
GET http://localhost:{{server.port}}/musik/album/get?genre=Kammermusik

###
GET http://localhost:{{server.port}}/musik/album/get?album=Fragile

###
GET http://localhost:{{server.port}}/musik/album/get?interpret=John

###
GET http://localhost:{{server.port}}/musik/album/get?komponist=Beethoven

###
GET http://localhost:{{server.port}}/musik/album/get?genre=Kammermusik

###
DELETE http://localhost:{{server.port}}/musik/album/remove?id=2352

###
GET http://localhost:{{server.port}}/musik/komponist/get?komponist=Beethov
