logging:
  level:
    org:
      jaudiotagger: warn
    root: info
musikserver:
  rootdir: F:/Cosmas/Musikarchiv
server:
  port: 8081
spring:
  datasource:
    password: mypostgres
    url: jdbc:postgresql://localhost:5432/musik
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
